#!/bin/bash

RESPONSE+="PID: $$
"
RESPONSE+="WHOAMI: $(whoami)
"
RESPONSE+="$(set | grep SOCAT)
"
RESPONSE+="$(set | grep "REQUEST_")
"
# RESPONSE+="-----
# "
# RESPONSE+="1234567890
# "
RESPONSE+="COMMAND: $@
"

echo_response_status_line
echo_response_default_headers
echo -e "Content-Type: text/plain; charset=utf-8\r"
echo -e "Content-Length: ${#RESPONSE}\r"
echo -e "\r"
echo "${RESPONSE}"

