#!/bin/bash

while getopts ":-:" options; do 
  unset VALUE
  if [[ ${!OPTIND} =~ ^-$ ]] || [[ ${!OPTIND} =~ ^[^-] ]];then
    VALUE=${!OPTIND}; OPTIND=$((OPTIND+1))
  fi
  case $options in
  *) case "$OPTARG" in
      f|foo) FOO=$VALUE;;
      b|boo) BOO=$VALUE;;
esac; esac; done; shift $((OPTIND-1))

echo "$0 foo:>$FOO<"
echo "$0 boo:>$BOO<"
echo " "

