#!/bin/bash

RESPONSE=""
RESPONSE+="Test
"

echo_response_status_line
echo_response_default_headers
echo -e "Content-Type: text/plain; charset=utf-8\r"
echo -e "Content-Length: ${#RESPONSE}\r"
echo -e "\r"

echo "${RESPONSE}"
